#!/bin/sh

fileroot=$1
sigma=$2

rm -f $fileroot.als

allstar << _ALLSTAR_
Y
$fileroot.fits
$fileroot.psf
$fileroot.ap
$fileroot.als

_ALLSTAR_



# Attached subtract image and try to get sources
# not intitially found twice
for loop in {1..2};
do

offset_value=$loop"00000"

subfileroot=$fileroot"s"
rm -f $subfileroot.coo
rm -f $subfileroot.ap
rm -f $subfileroot.off

daophot << _DAOPHOT_
AT $subfileroot
find
1,1
$subfileroot.coo
N
$sigma
$subfileroot.coo
OVERWRITE
Y
OFFSET
$subfileroot.coo
$offset_value,0,0,0
$subfileroot.off
EXIT
_DAOPHOT_

# If using WFCCD camera, just edges of footprint which is all noise
if [ ${subfileroot:0:5} == "fbccd" ];
then
        python ../scripts/remove_WFCCD_edge_noise.py $subfileroot.off
fi                                                                   

daophot << _DAOPHOT_
AT $subfileroot
PHO
photo
Y
$subfileroot.off
$subfileroot.ap
EXIT
_DAOPHOT_



rm -f $subfileroot.off # no longer needed


rm -f temp.psf
mv $fileroot.psf temp.psf
rm -f $fileroot.cmb

# Do ap phot on PSF phot file (now actual known stars)
# and append both the star-sub and original star lists
daophot << _DAOPHOT_
AT $fileroot
PHO
photo
Y
$fileroot.als
$fileroot.ap
OVERWRITE
APPEND
$fileroot.ap
$subfileroot.ap
$fileroot.cmb
EXIT
_DAOPHOT_

mv $fileroot.cmb $fileroot.ap

mv temp.psf $fileroot.psf
rm -f $fileroot.als

allstar << _ALLSTAR_
Y
$fileroot.fits
$fileroot.psf
$fileroot.ap
$fileroot.als

_ALLSTAR_

done # end sub-tracted image loop
