#!/bin/csh


set input = $1

set rawfile = $input:r

rm -f $rawfile.raw

# 6 order
daomaster << _DAOMASTER_
$input
2,1,2
99
6
20
















































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
$input
OVERWRITE
N
N
N
_DAOMASTER_



# 12 order
daomaster << _DAOMASTER_
$input
2,1,2
99
12
20



























































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
$input
OVERWRITE
N
N
N
_DAOMASTER_


# 20

daomaster << _DAOMASTER_
$input
2,1,2
99
20
20




































































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
Y
$rawfile
Y
$input
OVERWRITE
N
N
N
_DAOMASTER_
