#!/bin/sh

rm -f HV1003.mch

daomatch << _DAOMATCH_
sccd1089.als
HV1003.mch
sccd2074.als
Y
sccd2112.als
Y
sccd2113.als
Y
sccd3079.als
Y
sccd3119.als
Y
sccd4073.als
Y
sccd4117.als
Y
sccd5074.als
Y
sccd5115.als
Y
sccd6071.als
Y
sccd6111.als
Y
dbccd1096.als
Y
dbccd2117.als
Y
dbccd3110.als
Y
dbccd4101.als
Y
dbccd5109.als
Y
dbccd6092.als
Y
sccd1087.als
Y
sccd2073.als
Y
sccd2111.als
Y
sccd3078.als
Y
sccd3118.als
Y
sccd4072.als
Y
sccd4116.als
Y
sccd5073.als
Y
sccd5114.als
Y
sccd6070.als
Y
sccd6110.als
Y
dbccd1093.als
Y
dbccd2114.als
Y
dbccd3107.als
Y
dbccd4097.als
Y
dbccd4098.als
Y
dbccd5106.als
Y
dbccd6089.als
Y
dbccd1094.als
Y
dbccd2115.als
Y
dbccd3108.als
Y
dbccd4099.als
Y
dbccd5107.als
Y
dbccd6090.als
Y
sccd1090.als
Y
sccd2075.als
Y
sccd2114.als
Y
sccd3080.als
Y
sccd3120.als
Y
sccd4074.als
Y
sccd4118.als
Y
sccd5075.als
Y
sccd5116.als
Y
sccd6072.als
Y
sccd6112.als
Y
dbccd1097.als
Y
dbccd2118.als
Y
dbccd3111.als
Y
dbccd4102.als
Y
dbccd5110.als
Y
dbccd6093.als
Y
sccd1088.als
Y
sccd2072.als
Y
sccd2110.als
Y
sccd3077.als
Y
sccd3117.als
Y
sccd4071.als
Y
sccd4115.als
Y
sccd5072.als
Y
sccd5113.als
Y
sccd6069.als
Y
sccd6109.als
Y
dbccd1095.als
Y
dbccd2116.als
Y
dbccd3109.als
Y
dbccd4100.als
Y
dbccd5108.als
Y
dbccd6091.als
Y
EXIT
_DAOMATCH_

daomaster << _DAOMASTER_
HV1003.mch
3,0.5,6
99
6
20












































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV1003.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV1003.mch
3,0.5,6
99
12
20












































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV1003.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV1003.mch
3,0.5,6
99
20
20












































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
Y
HV1003.raw
Y
HV1003.mch
OVERWRITE
N
N
N
_DAOMASTER_

exit

rm -f HV1013.mch

daomatch << _DAOMATCH_
sccd1098.als
HV1013.mch
sccd2066.als
Y
sccd2108.als
Y
sccd3083.als
Y
sccd3123.als
Y
sccd4077.als
Y
sccd4121.als
Y
sccd5078.als
Y
sccd5119.als
Y
sccd6075.als
Y
sccd6115.als
Y
dbccd1106.als
Y
dbccd2132.als
Y
dbccd3126.als
Y
dbccd4121.als
Y
dbccd5129.als
Y
dbccd6112.als
Y
sccd1096.als
Y
sccd2065.als
Y
sccd2107.als
Y
sccd3082.als
Y
sccd3122.als
Y
sccd4076.als
Y
sccd4120.als
Y
sccd5077.als
Y
sccd5118.als
Y
sccd6074.als
Y
sccd6114.als
Y
dbccd1103.als
Y
dbccd2129.als
Y
dbccd3122.als
Y
dbccd4118.als
Y
dbccd5126.als
Y
dbccd6109.als
Y
dbccd1104.als
Y
dbccd2130.als
Y
dbccd2134.als
Y
dbccd3123.als
Y
dbccd3124.als
Y
dbccd4119.als
Y
dbccd5127.als
Y
dbccd6110.als
Y
sccd1099.als
Y
sccd1100.als
Y
sccd2067.als
Y
sccd2109.als
Y
sccd3084.als
Y
sccd3124.als
Y
sccd4078.als
Y
sccd4122.als
Y
sccd5079.als
Y
sccd5120.als
Y
sccd6076.als
Y
sccd6116.als
Y
dbccd1107.als
Y
dbccd2133.als
Y
dbccd3127.als
Y
dbccd4122.als
Y
dbccd5130.als
Y
dbccd6113.als
Y
sccd1097.als
Y
sccd2064.als
Y
sccd2106.als
Y
sccd3081.als
Y
sccd3121.als
Y
sccd4075.als
Y
sccd4119.als
Y
sccd5076.als
Y
sccd5117.als
Y
sccd6073.als
Y
sccd6113.als
Y
dbccd1105.als
Y
dbccd2131.als
Y
dbccd3125.als
Y
dbccd4120.als
Y
dbccd5128.als
Y
dbccd6111.als
Y
EXIT
_DAOMATCH_

daomaster << _DAOMASTER_
HV1013.mch
3,0.5,6
99
6
20













































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV1013.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV1013.mch
3,0.5,6
99
12
20













































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV1013.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV1013.mch
3,0.5,6
99
20
20













































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
Y
HV1013.raw
Y
HV1013.mch
OVERWRITE
N
N
N
_DAOMASTER_

rm -f HV2291.mch

daomatch << _DAOMATCH_
sccd1084.als
HV2291.mch
sccd2078.als
Y
sccd2117.als
Y
sccd3067.als
Y
sccd3115.als
Y
sccd4065.als
Y
sccd4109.als
Y
sccd5070.als
Y
sccd5111.als
Y
sccd6063.als
Y
sccd6107.als
Y
dbccd1091.als
Y
dbccd2112.als
Y
dbccd3105.als
Y
dbccd4095.als
Y
dbccd5104.als
Y
dbccd6087.als
Y
sccd1086.als
Y
sccd2077.als
Y
sccd2116.als
Y
sccd3066.als
Y
sccd3114.als
Y
sccd4064.als
Y
sccd4108.als
Y
sccd5069.als
Y
sccd5110.als
Y
sccd6062.als
Y
sccd6106.als
Y
dbccd1088.als
Y
dbccd2109.als
Y
dbccd3102.als
Y
dbccd4092.als
Y
dbccd5101.als
Y
dbccd6084.als
Y
dbccd1089.als
Y
dbccd2110.als
Y
dbccd3103.als
Y
dbccd4093.als
Y
dbccd5102.als
Y
dbccd6085.als
Y
sccd1083.als
Y
sccd2079.als
Y
sccd2118.als
Y
sccd3068.als
Y
sccd3116.als
Y
sccd4066.als
Y
sccd4110.als
Y
sccd5071.als
Y
sccd5112.als
Y
sccd6064.als
Y
sccd6108.als
Y
dbccd1092.als
Y
dbccd2113.als
Y
dbccd3106.als
Y
dbccd4096.als
Y
dbccd5105.als
Y
dbccd6088.als
Y
sccd1085.als
Y
sccd2076.als
Y
sccd2115.als
Y
sccd3065.als
Y
sccd3113.als
Y
sccd4063.als
Y
sccd4107.als
Y
sccd5068.als
Y
sccd5109.als
Y
sccd6061.als
Y
sccd6105.als
Y
dbccd1090.als
Y
dbccd2111.als
Y
dbccd3104.als
Y
dbccd4094.als
Y
dbccd5103.als
Y
dbccd6086.als
Y
EXIT
_DAOMATCH_

daomaster << _DAOMASTER_
HV2291.mch
3,0.5,6
99
6
20










































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV2291.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV2291.mch
3,0.5,6
99
12
20










































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV2291.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV2291.mch
3,0.5,6
99
20
20










































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
Y
HV2291.raw
Y
HV2291.mch
OVERWRITE
N
N
N
_DAOMASTER_

rm -f HV2749.mch

daomatch << _DAOMATCH_
sccd1062.als
HV2749.mch
sccd2094.als
Y
sccd2133.als
Y
sccd3099.als
Y
sccd4049.als
Y
sccd4093.als
Y
sccd6091.als
Y
dbccd1101.als
Y
dbccd2122.als
Y
dbccd3115.als
Y
dbccd4106.als
Y
dbccd5114.als
Y
dbccd6102.als
Y
sccd1057.als
Y
sccd1058.als
Y
sccd2093.als
Y
sccd2132.als
Y
sccd3098.als
Y
sccd4048.als
Y
sccd4092.als
Y
sccd6090.als
Y
dbccd1098.als
Y
dbccd2119.als
Y
dbccd3112.als
Y
dbccd4103.als
Y
dbccd5111.als
Y
dbccd6099.als
Y
dbccd1099.als
Y
dbccd2120.als
Y
dbccd3113.als
Y
dbccd4104.als
Y
dbccd5112.als
Y
dbccd6100.als
Y
sccd1064.als
Y
sccd2095.als
Y
sccd2096.als
Y
sccd2134.als
Y
sccd3100.als
Y
sccd4050.als
Y
sccd4094.als
Y
sccd6092.als
Y
dbccd1102.als
Y
dbccd2123.als
Y
dbccd3116.als
Y
dbccd4107.als
Y
dbccd5115.als
Y
dbccd6103.als
Y
sccd1060.als
Y
sccd2092.als
Y
sccd2131.als
Y
sccd3097.als
Y
sccd4047.als
Y
sccd4091.als
Y
sccd6089.als
Y
dbccd1100.als
Y
dbccd2121.als
Y
dbccd3114.als
Y
dbccd4105.als
Y
dbccd5113.als
Y
dbccd6101.als
Y
EXIT
_DAOMATCH_

daomaster << _DAOMASTER_
HV2749.mch
3,0.5,6
99
6
20




























































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV2749.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV2749.mch
3,0.5,6
99
12
20




























































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV2749.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV2749.mch
3,0.5,6
99
20
20




























































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
Y
HV2749.raw
Y
HV2749.mch
OVERWRITE
N
N
N
_DAOMASTER_

rm -f HV2793.mch

daomatch << _DAOMATCH_
sccd1066.als
HV2793.mch
sccd2090.als
Y
sccd2129.als
Y
sccd3055.als
Y
sccd3103.als
Y
sccd4053.als
Y
sccd4097.als
Y
sccd5053.als
Y
sccd5055.als
Y
sccd5099.als
Y
sccd6095.als
Y
dbccd2074.als
Y
dbccd3120.als
Y
dbccd4116.als
Y
dbccd5124.als
Y
dbccd6107.als
Y
sccd1068.als
Y
sccd1069.als
Y
sccd2089.als
Y
sccd2128.als
Y
sccd3054.als
Y
sccd3102.als
Y
sccd4052.als
Y
sccd4096.als
Y
sccd5052.als
Y
sccd5098.als
Y
sccd6094.als
Y
dbccd2071.als
Y
dbccd3117.als
Y
dbccd4113.als
Y
dbccd5121.als
Y
dbccd6104.als
Y
dbccd2072.als
Y
dbccd3118.als
Y
dbccd4114.als
Y
dbccd5122.als
Y
dbccd6105.als
Y
sccd1065.als
Y
sccd2091.als
Y
sccd2130.als
Y
sccd3056.als
Y
sccd3104.als
Y
sccd4054.als
Y
sccd4098.als
Y
sccd5054.als
Y
sccd5100.als
Y
sccd6096.als
Y
dbccd2075.als
Y
dbccd3121.als
Y
dbccd4117.als
Y
dbccd5125.als
Y
dbccd6108.als
Y
sccd1067.als
Y
sccd2088.als
Y
sccd2127.als
Y
sccd3053.als
Y
sccd3101.als
Y
sccd4051.als
Y
sccd4095.als
Y
sccd5051.als
Y
sccd5097.als
Y
sccd6093.als
Y
dbccd2073.als
Y
dbccd3119.als
Y
dbccd4115.als
Y
dbccd5123.als
Y
dbccd6106.als
Y
EXIT
_DAOMATCH_

daomaster << _DAOMASTER_
HV2793.mch
3,0.5,6
99
6
20



































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV2793.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV2793.mch
3,0.5,6
99
12
20



































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV2793.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV2793.mch
3,0.5,6
99
20
20



































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
Y
HV2793.raw
Y
HV2793.mch
OVERWRITE
N
N
N
_DAOMASTER_

rm -f HV2836.mch

daomatch << _DAOMATCH_
sccd6098.als
HV2836.mch
EXIT
_DAOMATCH_

daomaster << _DAOMASTER_
HV2836.mch
3,0.5,6
99
6
20

19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV2836.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV2836.mch
3,0.5,6
99
12
20

19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV2836.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV2836.mch
3,0.5,6
99
20
20

19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
Y
HV2836.raw
Y
HV2836.mch
OVERWRITE
N
N
N
_DAOMASTER_

rm -f HV6098.mch

daomatch << _DAOMATCH_
sccd1075.als
HV6098.mch
sccd2082.als
Y
sccd2121.als
Y
sccd3063.als
Y
sccd3111.als
Y
sccd4061.als
Y
sccd4105.als
Y
sccd5066.als
Y
sccd5107.als
Y
sccd6103.als
Y
dbccd1080.als
Y
dbccd2102.als
Y
dbccd3095.als
Y
dbccd4080.als
Y
dbccd5089.als
Y
dbccd6077.als
Y
sccd1077.als
Y
sccd2081.als
Y
sccd2120.als
Y
sccd3062.als
Y
sccd3110.als
Y
sccd4060.als
Y
sccd4104.als
Y
sccd5065.als
Y
sccd5106.als
Y
sccd6102.als
Y
dbccd1075.als
Y
dbccd1076.als
Y
dbccd2098.als
Y
dbccd2099.als
Y
dbccd3092.als
Y
dbccd4076.als
Y
dbccd4079.als
Y
dbccd5086.als
Y
dbccd6074.als
Y
dbccd1077.als
Y
dbccd1078.als
Y
dbccd2100.als
Y
dbccd3093.als
Y
dbccd4077.als
Y
dbccd5087.als
Y
dbccd6075.als
Y
sccd1074.als
Y
sccd2083.als
Y
sccd2122.als
Y
sccd3064.als
Y
sccd3112.als
Y
sccd4062.als
Y
sccd4106.als
Y
sccd5067.als
Y
sccd5108.als
Y
sccd6104.als
Y
dbccd1081.als
Y
dbccd1082.als
Y
dbccd2103.als
Y
dbccd3096.als
Y
dbccd4081.als
Y
dbccd5090.als
Y
dbccd6078.als
Y
sccd1076.als
Y
sccd2080.als
Y
sccd2119.als
Y
sccd3061.als
Y
sccd3109.als
Y
sccd4059.als
Y
sccd4103.als
Y
sccd5064.als
Y
sccd5105.als
Y
sccd6101.als
Y
dbccd1079.als
Y
dbccd2101.als
Y
dbccd3094.als
Y
dbccd4078.als
Y
dbccd5088.als
Y
dbccd6076.als
Y
EXIT
_DAOMATCH_

daomaster << _DAOMASTER_
HV6098.mch
3,0.5,6
99
6
20











































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV6098.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV6098.mch
3,0.5,6
99
12
20











































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV6098.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV6098.mch
3,0.5,6
99
20
20











































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
Y
HV6098.raw
Y
HV6098.mch
OVERWRITE
N
N
N
_DAOMASTER_

rm -f HV876.mch

daomatch << _DAOMATCH_
dbccd2069.als
HV876.mch
dbccd3142.als
Y
dbccd4138.als
Y
dbccd5068.als
Y
dbccd6132.als
Y
dbccd2066.als
Y
dbccd3139.als
Y
dbccd4133.als
Y
dbccd4134.als
Y
dbccd5062.als
Y
dbccd5063.als
Y
dbccd5064.als
Y
dbccd5065.als
Y
dbccd6129.als
Y
dbccd2067.als
Y
dbccd3140.als
Y
dbccd4135.als
Y
dbccd4136.als
Y
dbccd5066.als
Y
dbccd6130.als
Y
dbccd2070.als
Y
dbccd3143.als
Y
dbccd4139.als
Y
dbccd5069.als
Y
dbccd6133.als
Y
dbccd2068.als
Y
dbccd3141.als
Y
dbccd4137.als
Y
dbccd5067.als
Y
dbccd6131.als
Y
EXIT
_DAOMATCH_

daomaster << _DAOMASTER_
HV876.mch
3,0.5,6
99
6
20






























19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV876.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV876.mch
3,0.5,6
99
12
20






























19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV876.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV876.mch
3,0.5,6
99
20
20






























19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
Y
HV876.raw
Y
HV876.mch
OVERWRITE
N
N
N
_DAOMASTER_

rm -f HV878.mch

daomatch << _DAOMATCH_
sccd1102.als
HV878.mch
sccd2060.als
Y
sccd2104.als
Y
sccd3087.als
Y
sccd3127.als
Y
sccd4081.als
Y
sccd4125.als
Y
sccd5082.als
Y
sccd5123.als
Y
sccd6079.als
Y
sccd6119.als
Y
dbccd1060.als
Y
dbccd2083.als
Y
dbccd4064.als
Y
dbccd5079.als
Y
dbccd6067.als
Y
sccd1104.als
Y
sccd2059.als
Y
sccd2103.als
Y
sccd3086.als
Y
sccd3126.als
Y
sccd4080.als
Y
sccd4124.als
Y
sccd5081.als
Y
sccd5122.als
Y
sccd6078.als
Y
sccd6118.als
Y
dbccd1055.als
Y
dbccd1056.als
Y
dbccd2086.als
Y
dbccd4061.als
Y
dbccd5075.als
Y
dbccd5076.als
Y
dbccd6063.als
Y
dbccd6064.als
Y
dbccd1057.als
Y
dbccd1058.als
Y
dbccd2085.als
Y
dbccd4062.als
Y
dbccd5077.als
Y
dbccd6065.als
Y
sccd1101.als
Y
sccd2061.als
Y
sccd2062.als
Y
sccd2105.als
Y
sccd3088.als
Y
sccd3128.als
Y
sccd4082.als
Y
sccd4126.als
Y
sccd5083.als
Y
sccd5124.als
Y
sccd6080.als
Y
sccd6120.als
Y
dbccd1061.als
Y
dbccd1062.als
Y
dbccd2082.als
Y
dbccd4065.als
Y
dbccd5080.als
Y
dbccd6068.als
Y
sccd1103.als
Y
sccd2058.als
Y
sccd2102.als
Y
sccd3085.als
Y
sccd3125.als
Y
sccd4079.als
Y
sccd4123.als
Y
sccd5080.als
Y
sccd5121.als
Y
sccd6077.als
Y
sccd6117.als
Y
dbccd1059.als
Y
dbccd2084.als
Y
dbccd4063.als
Y
dbccd5078.als
Y
dbccd6066.als
Y
EXIT
_DAOMATCH_

daomaster << _DAOMASTER_
HV878.mch
3,0.5,6
99
6
20











































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV878.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV878.mch
3,0.5,6
99
12
20











































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV878.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV878.mch
3,0.5,6
99
20
20











































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
Y
HV878.raw
Y
HV878.mch
OVERWRITE
N
N
N
_DAOMASTER_

rm -f HV879.mch

daomatch << _DAOMATCH_
dbccd3080.als
HV879.mch
dbccd3076.als
Y
dbccd3077.als
Y
dbccd3078.als
Y
dbccd3081.als
Y
dbccd3079.als
Y
EXIT
_DAOMATCH_

daomaster << _DAOMASTER_
HV879.mch
3,0.5,6
99
6
20






19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV879.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV879.mch
3,0.5,6
99
12
20






19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV879.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV879.mch
3,0.5,6
99
20
20






19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
Y
HV879.raw
Y
HV879.mch
OVERWRITE
N
N
N
_DAOMASTER_

rm -f HV886.mch

daomatch << _DAOMATCH_
sccd2056.als
HV886.mch
sccd2099.als
Y
sccd2100.als
Y
sccd3091.als
Y
sccd3131.als
Y
sccd4085.als
Y
sccd4129.als
Y
sccd5086.als
Y
sccd5127.als
Y
sccd6083.als
Y
sccd6123.als
Y
dbccd1067.als
Y
dbccd2091.als
Y
dbccd3085.als
Y
dbccd4074.als
Y
dbccd5084.als
Y
dbccd6072.als
Y
sccd1105.als
Y
sccd2063.als
Y
sccd2098.als
Y
sccd3090.als
Y
sccd3130.als
Y
sccd4084.als
Y
sccd4128.als
Y
sccd5085.als
Y
sccd5126.als
Y
sccd6082.als
Y
sccd6122.als
Y
dbccd1063.als
Y
dbccd1064.als
Y
dbccd2087.als
Y
dbccd2088.als
Y
dbccd3082.als
Y
dbccd4071.als
Y
dbccd5081.als
Y
dbccd6069.als
Y
dbccd1065.als
Y
dbccd2089.als
Y
dbccd3083.als
Y
dbccd4072.als
Y
dbccd5082.als
Y
dbccd6070.als
Y
sccd2057.als
Y
sccd2101.als
Y
sccd3092.als
Y
sccd3132.als
Y
sccd4086.als
Y
sccd4130.als
Y
sccd5087.als
Y
sccd5128.als
Y
sccd6084.als
Y
sccd6124.als
Y
dbccd1068.als
Y
dbccd2092.als
Y
dbccd3086.als
Y
dbccd4075.als
Y
dbccd5085.als
Y
dbccd6073.als
Y
sccd1106.als
Y
sccd2054.als
Y
sccd2055.als
Y
sccd2097.als
Y
sccd3089.als
Y
sccd3129.als
Y
sccd4083.als
Y
sccd4127.als
Y
sccd5084.als
Y
sccd5125.als
Y
sccd6081.als
Y
sccd6121.als
Y
dbccd1066.als
Y
dbccd2090.als
Y
dbccd3084.als
Y
dbccd4073.als
Y
dbccd5083.als
Y
dbccd6071.als
Y
EXIT
_DAOMATCH_

daomaster << _DAOMASTER_
HV886.mch
3,0.5,6
99
6
20












































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV886.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV886.mch
3,0.5,6
99
12
20












































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV886.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV886.mch
3,0.5,6
99
20
20












































































19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
Y
HV886.raw
Y
HV886.mch
OVERWRITE
N
N
N
_DAOMASTER_

rm -f HV902.mch

daomatch << _DAOMATCH_
dbccd1086.als
HV902.mch
dbccd2107.als
Y
dbccd3100.als
Y
dbccd4090.als
Y
dbccd5094.als
Y
dbccd6082.als
Y
dbccd1083.als
Y
dbccd2104.als
Y
dbccd3097.als
Y
dbccd4087.als
Y
dbccd5091.als
Y
dbccd6079.als
Y
dbccd1084.als
Y
dbccd2105.als
Y
dbccd3098.als
Y
dbccd4088.als
Y
dbccd5092.als
Y
dbccd6080.als
Y
dbccd1087.als
Y
dbccd2108.als
Y
dbccd3101.als
Y
dbccd4091.als
Y
dbccd5095.als
Y
dbccd6083.als
Y
dbccd1085.als
Y
dbccd2106.als
Y
dbccd3099.als
Y
dbccd4089.als
Y
dbccd5093.als
Y
dbccd6081.als
Y
EXIT
_DAOMATCH_

daomaster << _DAOMASTER_
HV902.mch
3,0.5,6
99
6
20






























19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV902.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV902.mch
3,0.5,6
99
12
20






























19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
N
Y
HV902.mch
OVERWRITE
N
N
N
_DAOMASTER_

daomaster << _DAOMASTER_
HV902.mch
3,0.5,6
99
20
20






























19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
N
N
N
Y
HV902.raw
Y
HV902.mch
OVERWRITE
N
N
N
_DAOMASTER_

