#!/bin/sh

fileroot=$1
sigma=$2



rm -f $fileroot.coo

daophot << _DAOPHOT_
at $fileroot
find
1,1
$fileroot.coo
N
$sigma
$fileroot.coo
OVERWRITE
Y
EXIT
_DAOPHOT_


# If using WFCCD camera, just edges of footprint which is all noise
if [ ${fileroot:0:5} == "fbccd" ];
then
	python ../scripts/remove_WFCCD_edge_noise.py $fileroot.coo
fi
