#!/bin/sh

fileroot=$1

# Estimate the FWHM of stars in the 
# current image using the daophot template
# file that will have roughly the right parameters

rm -f daophot.opt
cp daophot_template.opt daophot.opt

# $1 is file, $2 is sigma level. Deault set to high to
# measure FWHM of real stars
../scripts/daophot_find_script $fileroot 3.5

# Estimate the FWHM for stars in the image
# Pass the fileroot name and the number of stars
# to use for the average

est_FWHM=$(python ../scripts/measure_FWHM.py $fileroot 500)
echo $est_FWHM

# Change FWHM value
curr_FWHM=`grep "FW" daophot_template.opt`
new_FWHM=`echo $curr_FWHM | sed 's/=.*//'`"=     ""$est_FWHM" 
sed "s/$curr_FWHM/$new_FWHM/" < daophot_template.opt > daophot_temp.opt

# Update PS value to 4x FWHM
est_PS=`echo  "$est_FWHM * 4" | bc`
curr_PS=`grep "PS" daophot_template.opt`
new_PS=`echo $curr_PS | sed 's/=.*//'`"=     ""$est_PS" 
sed "s/$curr_PS/$new_PS/" < daophot_temp.opt > daophot.opt

# Remove intermediate daophot.opt file
rm -f daophot_temp.opt

