#!/bin/sh

source activate astroconda



# Perform any necessary work 
# on original images and link
# result to daophot_ready_images

./prep_images_for_daophot_script


# Loop through each image for an initial
# photometry run.

(
cd ../phot

# Remove existing files
for file in *.fits; do unlink $file; done
#rm -f *.srt
#rm -f *.nst
#rm -f *.nei
#rm -f *.psf
#rm -f *.lst
#rm -f *.coo
#rm -f *.ap
#rm -f *.als
#rm -f *s.fits

# Link current daophot-ready images
ln -s ../daophot_ready_images/*.fits .

# Link photometry option file templates
for file in *opt; do unlink $file; done
ln -s ../option_files/*opt .

for file in *.fits; 
do 

	fileroot=${file%.*}

	# Setting the detection threshold
	if [ ${fileroot:0:4} == "sccd" ];
	then
		daophot_threshold=3.5		
	fi
	if [ ${fileroot:0:4} == "dbcc" ];	
	then
		daophot_threshold=2.5
	fi

	# Skip existing or already run images
	if [ -s $fileroot".als" ]; 
	then 
		#echo $fileroot".als" "file exists";
		continue
	fi


	if [ $fileroot != "sccd1057" ];then continue; fi



	# Estimate the FWHM of stars in the 
        # current image using the daophot template
        # file that will have roughly the right parameters

	../scripts/generate_daophot_allstar_file $fileroot 

	# Get full star *.coo list with updated FWHM

	../scripts/daophot_find_script $fileroot $daophot_threshold	
	
	# Get aperture photometry from full star *.coo list

	../scripts/daophot_phot_script $fileroot	

	# Sort aperture photometry for brightest stars,
	# Check which stars are successfully measured
	# in all apertures (down to a mag limit) 
	# to within a few FWHM 

	../scripts/daophot_sort_ap_file $fileroot
	
	# Generate PSF based on the bright and isolated stars 

	../scripts/create_psf_star_list	$fileroot

	# Run allstar on star catalog

	../scripts/allstar_script $fileroot $daophot_threshold


	
done # End looping through images in ./phot/
)



# Align photometry files and create merged catalog
# of single epoch observations                    	








# Remove all symbolic links

#find ../ -type l -delete






# Calibrate allstar photometry to standards

# Average single epoch observations



