#!/bin/sh

source activate astroconda

# Perform any necessary work 
# on original images and link
# result to daophot_ready_images

./prep_images_for_daophot_script


# Loop through each image for an initial
# photometry run.

(
cd ../phot

# Remove existing files
for file in *.fits; do unlink $file; done

# Link current daophot-ready images
ln -s ../daophot_ready_images/*.fits .

# Link photometry option file templates
for file in *opt; do unlink $file; done
ln -s ../option_files/*opt .

for file in *.fits; 
do 

	fileroot=${file%.*}

	# Estimate the FWHM of stars in the 
        # current image using the daophot template
        # file that will have roughly the right parameters

	../scripts/generate_daophot_allstar_file $fileroot	

	# Get full star *.coo list with updated FWHM

	../scripts/daophot_find_script $fileroot 3.5	
	
	# Get aperture photometry from full star *.coo list

	../scripts/daophot_phot_script $fileroot	

	# Sort aperture photometry for brightest stars,
	# Check which stars are successfully measured
	# in all apertures (down to a mag limit) 
	# to within a few FWHM 

	../scripts/daophot_sort_ap_file $fileroot
	
	# Generate PSF based on the bright and isolated stars 
	
	
	# Run allstar on preliminary star catalog
	
	
	# Calibrate allstar photometry to standards
	
done # End looping through images
)
	

# Remove all symbolic links

find ../ -type l -delete




# Align photometry files and create merged catalog
# of single epoch observations


# Average single epoch observations



